from fastapi import APIRouter, Depends, status
from sqlalchemy.orm import Session

from app.api.deps import require_planner
from app.database.session import get_db
from app.schemas.auth import AuthUser
from app.schemas.report import ReportCreate, ReportRead
from app.services import report_service

router = APIRouter()


@router.get("/planner/reports", response_model=list[ReportRead])
def list_reports(
    current_user: AuthUser = Depends(require_planner),
    db: Session = Depends(get_db),
) -> list[ReportRead]:
    """List all reports generated by the authenticated planner (newest first)."""
    return report_service.list_reports(db, current_user.id)


@router.post(
    "/planner/reports",
    response_model=ReportRead,
    status_code=status.HTTP_201_CREATED,
)
def create_report(
    payload: ReportCreate,
    current_user: AuthUser = Depends(require_planner),
    db: Session = Depends(get_db),
) -> ReportRead:
    """Generate a new site-assessment report from explicitly selected site IDs."""
    return report_service.create_report(db, current_user.id, payload)


@router.get("/planner/reports/{report_id}", response_model=ReportRead)
def get_report(
    report_id: str,
    current_user: AuthUser = Depends(require_planner),
    db: Session = Depends(get_db),
) -> ReportRead:
    """Fetch a single report by ID (ownership-checked)."""
    return report_service.get_report(db, current_user.id, report_id)


@router.delete(
    "/planner/reports/{report_id}",
    status_code=status.HTTP_204_NO_CONTENT,
)
def delete_report(
    report_id: str,
    current_user: AuthUser = Depends(require_planner),
    db: Session = Depends(get_db),
) -> None:
    """Delete a report (ownership-checked)."""
    report_service.delete_report(db, current_user.id, report_id)
