from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database.session import Base, utcnow


class PlannerReport(Base):
    """A site-assessment report generated by a planner.

    `site_ids` is stored as a JSON-encoded list of site ID strings so we
    avoid a separate join table while keeping the report self-contained.
    The service layer is responsible for encoding/decoding the list.
    """

    __tablename__ = "planner_reports"

    id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    user_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    # JSON-encoded list of site IDs, e.g. '["site_abc", "site_def"]'
    site_ids_json: Mapped[str] = mapped_column(Text, nullable=False)
    division: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
    )
